-- CREATE USER 'notname'@'localhost' IDENTIFIED BY '123';
-- 
-- GRANT ALL PRIVILEGES ON * . * TO 'notname'@'localhost';
-- 
-- SELECT * FROM mysql.user;
-- 
-- select * from INFORMATION_SCHEMA.PROCESSLIST;
-- 
-- 

DROP DATABASE IF EXISTS NOTNAME;
CREATE DATABASE NOTNAME
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;
USE NOTNAME;


CREATE TABLE CLIENTE (
CLI_nCOD BIGINT PRIMARY KEY AUTO_INCREMENT AUTO_INCREMENT,
CLI_cNOME VARCHAR(70),
CLI_cRG VARCHAR(15),
CLI_cCPF INT(11) UNIQUE,
CLI_dDTNASC DATE,
CLI_cGENERO CHAR(1),
CLI_nTRESIDENCIAL INT(10),
CLI_nTCELULAR INT(11),
CLI_nTCOMERCIAL INT(10),
CLI_cEMAIL VARCHAR(100) UNIQUE,
CLI_cLOGIN VARCHAR(20) UNIQUE,
CLI_cSENHA VARCHAR(20),
CLI_dDTULTIMO_ACESSO TIMESTAMP NULL DEFAULT NULL,
CLI_cSTATUS TINYINT,
CLI_tPREFERENCIA TEXT DEFAULT NULL
)ENGINE = INNODB;

CREATE TABLE CLIENTE_COMPRA (
CLI_COMPRA_nID INT PRIMARY KEY AUTO_INCREMENT,
CLI_nCOD BIGINT,
COMPRA_nID INT,
FOREIGN KEY(CLI_nCOD) REFERENCES CLIENTE (CLI_nCOD)
)ENGINE = INNODB;

CREATE TABLE COMPRA (
COMPRA_nID INT PRIMARY KEY AUTO_INCREMENT,
COMPRA_nVLRTOTALVENDA DOUBLE(8,2),
COMPRA_dtDTSEPARACAO TIMESTAMP NULL DEFAULT NULL ,
COMPRA_dtDTCOMPRA TIMESTAMP NULL DEFAULT NULL ,
COMPRA_cCODRASTREIO VARCHAR(15)
)ENGINE = INNODB;

CREATE TABLE ENDERECO (
END_nID BIGINT PRIMARY KEY AUTO_INCREMENT,
END_nCEP INT(8),
END_cLOGRADOURO VARCHAR(250),
END_cCIDADE VARCHAR(150),
END_cBAIRRO VARCHAR(150),
END_nNUMERO VARCHAR(7),
END_cCOMPLEMENTO VARCHAR(150),
UF_nID INT
)ENGINE = INNODB;

CREATE TABLE UF (
UF_nID INT PRIMARY KEY AUTO_INCREMENT,
UF_cUF CHAR(2),
UF_cDESCRICAO VARCHAR(150)
)ENGINE = INNODB;

CREATE TABLE PRODUTO (
PRODUTO_nID INT PRIMARY KEY AUTO_INCREMENT,
PRODUTO_cDESC VARCHAR(50),
PRODUTO_cDESCCOMPLETA TEXT,
PRODUTO_nSTATUS TINYINT,
MARCA_nID INT,
MODELO_nID INT
)ENGINE = INNODB;

CREATE TABLE MARCA (
MARCA_nID INT PRIMARY KEY AUTO_INCREMENT,
MARCA_cDESC VARCHAR(250),
MARCA_nSTATUS TINYINT
)ENGINE = INNODB;

CREATE TABLE MODELO (
MODELO_nID INT PRIMARY KEY AUTO_INCREMENT,
MODELO_cNOME VARCHAR(150),
MODELO_cTAMANHO VARCHAR(10),
MODELO_cCOR VARCHAR(20),
MODELO_nVLR_VENDA DOUBLE(8,2),
MODELO_nSTATUS TINYINT,
MODELO_nVLR_COMPRA DOUBLE(8,2),
MODELO_dDATA_COMPRA DATE,
MODELO_nDESCONTO DOUBLE(8,2),
MODELO_nQTD_ESTOQUE FLOAT
)ENGINE = INNODB;

CREATE TABLE PRODUTO_CATEGORIA (
PRODUTO_CATEGORIA_nID INT PRIMARY KEY AUTO_INCREMENT,
CATEGORIA_nID INT,
PRODUTO_nID INT,
FOREIGN KEY(PRODUTO_nID) REFERENCES PRODUTO (PRODUTO_nID)
)ENGINE = INNODB;

CREATE TABLE COMPRA_ESTOQUE (
COMPRA_ESTOQUE_nID INT PRIMARY KEY AUTO_INCREMENT,
COMPRA_ESTOQUE_nVALORTOTAL DOUBLE(8,2),
COMPRA_ESTOQUE_dDATA DATE
)ENGINE = INNODB;

CREATE TABLE MODELO_COMPRA_ESTOQUE (
MOD_COMP_ESTOQUE_nID INT PRIMARY KEY AUTO_INCREMENT,
MODELO_COMPRA_ESTOQUE_nQTD FLOAT,
MODELO_nID INT,
COMPRA_ESTOQUE_nID INT,
FOREIGN KEY(MODELO_nID) REFERENCES MODELO (MODELO_nID),
FOREIGN KEY(COMPRA_ESTOQUE_nID) REFERENCES COMPRA_ESTOQUE (COMPRA_ESTOQUE_nID)
)ENGINE = INNODB;

CREATE TABLE USUARIO (
USR_nCOD INT PRIMARY KEY AUTO_INCREMENT,
USR_cSTATUS TINYINT,
USR_cLOGIN VARCHAR(20),
USR_cSENHA VARCHAR(20),
USR_cNOME VARCHAR(100),
USR_nPERMISSAO TINYINT,
USR_EMAIL VARCHAR(100)
)ENGINE = INNODB;

CREATE TABLE PREFERENCIAS_SISTEMA (
ID_PREF_SISTEMA INT PRIMARY KEY AUTO_INCREMENT,
NUM_CLIQUES BIGINT,
PADRAO_SISTEMA TEXT
)ENGINE = INNODB;

CREATE TABLE COMPRA_PRODUTO (
COMPRA_PRODUTO_nID INT PRIMARY KEY AUTO_INCREMENT,
COMPRA_nID INT,
PRODUTO_nID INT,
COMPRA_PRODUTO_QDTE FLOAT,
FOREIGN KEY(COMPRA_nID) REFERENCES COMPRA (COMPRA_nID),
FOREIGN KEY(PRODUTO_nID) REFERENCES PRODUTO (PRODUTO_nID)
)ENGINE = INNODB;

CREATE TABLE CATEGORIA (
CATEGORIA_nID INT PRIMARY KEY AUTO_INCREMENT,
CATEGORIA_cDESC VARCHAR(99)
)ENGINE = INNODB;

CREATE TABLE CLIENTE_ENDERECO (
CLI_END_nID INT PRIMARY KEY AUTO_INCREMENT,
END_nID BIGINT,
CLI_nCOD BIGINT,
FOREIGN KEY(END_nID) REFERENCES ENDERECO (END_nID),
FOREIGN KEY(CLI_nCOD) REFERENCES CLIENTE (CLI_nCOD)
)ENGINE = INNODB;

CREATE TABLE COMPRA_STATUS (
COMP_STA_nID INT PRIMARY KEY AUTO_INCREMENT,
STATUS_nID INT,
COMPRA_nID INT,
COMPRA_STATUS_dDT_ATUALIZACAO TIMESTAMP NULL DEFAULT NULL,
FOREIGN KEY(COMPRA_nID) REFERENCES COMPRA (COMPRA_nID)
)ENGINE = INNODB;

CREATE TABLE STATUS_COMPRA (
STATUS_nID INT PRIMARY KEY AUTO_INCREMENT,
STATUS_cDESC VARCHAR(250)
)ENGINE = INNODB;

ALTER TABLE CLIENTE_COMPRA ADD FOREIGN KEY(COMPRA_nID) REFERENCES COMPRA (COMPRA_nID);
ALTER TABLE ENDERECO ADD FOREIGN KEY(UF_nID) REFERENCES UF (UF_nID);
ALTER TABLE PRODUTO ADD FOREIGN KEY(MARCA_nID) REFERENCES MODELO (MODELO_nID);
ALTER TABLE PRODUTO ADD FOREIGN KEY(MODELO_nID) REFERENCES MODELO (MODELO_nID);
ALTER TABLE PRODUTO_CATEGORIA ADD FOREIGN KEY(CATEGORIA_nID) REFERENCES CATEGORIA (CATEGORIA_nID);
ALTER TABLE COMPRA_STATUS ADD FOREIGN KEY(STATUS_nID) REFERENCES STATUS (STATUS_nID);
