<?php
$sql = "SELECT 
(SELECT SUM(VENDA_nVLRTOTALVENDA) FROM VENDA) AS VALOR_VENDA,
(SELECT count(*) FROM VENDA) AS NUMERO_VENDAS,
(SELECT COUNT(DISTINCT CLI_nCOD) FROM VENDA) AS CLI_VENDAS,
(SELECT COUNT(*) FROM VENDA_MODELO INNER JOIN VENDA ON VENDA.VENDA_nID = VENDA_MODELO.VENDA_nID) AS NUMERO_MODELOS
";


?>